name: Build CV document
on:
  pull_request:
    branches:    
      - master
  push:
    branches:    
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/typst/typst:v0.10.0
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: make all
      run: make all
