name: Build CV document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
      - name: update
        uses: actions/upload-artifact@v2
        with:
          name: compiled
          path: cv.pdf
